import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const mainSource = readFileSync(new URL('../src/main.ts', import.meta.url), 'utf8');
const scene0631Source = readFileSync(new URL('../src/scenes/CareerMinigameBoardScene0631.ts', import.meta.url), 'utf8');
const scene063Source = readFileSync(new URL('../src/scenes/CareerMinigameBoardScene063.ts', import.meta.url), 'utf8');
const scene069Source = readFileSync(new URL('../src/scenes/CareerMinigameBoardScene069.ts', import.meta.url), 'utf8');
const authoritySource = readFileSync(new URL('../src/core/authority.ts', import.meta.url), 'utf8');

assert(mainSource.includes('CareerMinigameBoardScene069 as ActiveBoardScene'));
assert(scene069Source.includes('extends CareerMinigameBoardScene0682'));
assert(!scene069Source.includes('submitIntent('));
assert(!scene069Source.includes('Math.random'));
assert(scene0631Source.includes('extends CareerMinigameBoardScene063'));
assert(scene0631Source.includes('this.centerActivePlayer0631();'));
assert(scene0631Source.includes('this.cameras.main.centerOn(token.x, token.y)'));
assert(scene0631Source.includes('if (internals.overviewMode) return;'));
assert(scene0631Source.includes('this.cameras.main.stopFollow()'));
assert(scene0631Source.includes('CAMERA_EDGE_MARGIN_0631 = 96'));
assert(scene0631Source.includes('camera.setBounds(left, top, right - left, bottom - top)'));
assert(scene0631Source.includes('halfViewX'));
assert(scene0631Source.includes('halfViewY'));
assert(scene063Source.includes('const TOKEN_SCALE_063 = 0.82'));
assert(scene063Source.includes('const LANDING_CONTENT_SCALE_063 = 1.18'));
assert(scene063Source.includes('return 27'));
assert(!scene0631Source.includes('submitIntent('));
assert(!scene0631Source.includes('Math.random'));
assert(authoritySource.includes('autoResolveParityBranches062'));
assert(scene0631Source.includes('ACTIVE TOKEN LUÔN Ở GIỮA'));
console.log('[active-player-center-lock-0631] PASS historical center-lock retained beneath 0.1.69 wrapper');
