import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { MEMEME_BUILD } from '../src/buildInfo';
import { movementStepDisposition } from '../src/ui/movementVisualPolicy';

assert.equal(movementStepDisposition({ x: 10, y: 10 }, { x: 10, y: 10 }, { x: 90, y: 10 }), 'animate');
assert.equal(movementStepDisposition({ x: 90, y: 10 }, { x: 10, y: 10 }, { x: 90, y: 10 }), 'duplicate');
assert.equal(movementStepDisposition({ x: 150, y: 10 }, { x: 10, y: 10 }, { x: 90, y: 10 }), 'stale');
assert.equal(movementStepDisposition({ x: 13, y: 13 }, { x: 10, y: 10 }, { x: 90, y: 10 }), 'animate');

const bgm = await readFile('src/audio/bgmController.ts', 'utf8');
const money = await readFile('src/scenes/TurnStakesBoardScene.ts', 'utf8');
const presentation = await readFile('src/ui/MatchPresentationLayer.ts', 'utf8');
const dice = await readFile('src/scenes/TurnOrderScene048.ts', 'utf8');
const board048 = await readFile('src/scenes/CareerMinigameBoardScene048.ts', 'utf8');
const board056 = await readFile('src/scenes/CareerMinigameBoardScene056.ts', 'utf8');
const board0561 = await readFile('src/scenes/CareerMinigameBoardScene0561.ts', 'utf8');
const board057 = await readFile('src/scenes/CareerMinigameBoardScene057.ts', 'utf8');
const board058 = await readFile('src/scenes/CareerMinigameBoardScene058.ts', 'utf8');
const board059 = await readFile('src/scenes/CareerMinigameBoardScene059.ts', 'utf8');
const board060 = await readFile('src/scenes/CareerMinigameBoardScene060.ts', 'utf8');
const board061 = await readFile('src/scenes/CareerMinigameBoardScene061.ts', 'utf8');
const board062 = await readFile('src/scenes/CareerMinigameBoardScene062.ts', 'utf8');
const board0651 = await readFile('src/scenes/CareerMinigameBoardScene0651.ts', 'utf8');
const board066 = await readFile('src/scenes/CareerMinigameBoardScene066.ts', 'utf8');
const board068 = await readFile('src/scenes/CareerMinigameBoardScene068.ts', 'utf8');
const board0681 = await readFile('src/scenes/CareerMinigameBoardScene0681.ts', 'utf8');
const board0682 = await readFile('src/scenes/CareerMinigameBoardScene0682.ts', 'utf8');
const releaseGuard066 = await readFile('src/core/cpuReleaseResume066.ts', 'utf8');
const picker = await readFile('src/ui/CardHandPicker.ts', 'utf8');
const main = await readFile('src/main.ts', 'utf8');
const lobby = await readFile('src/scenes/LocalLobbyScene.ts', 'utf8');
const setup = await readFile('src/scenes/SetupScene.ts', 'utf8');

const playRoundBlock = bgm.slice(bgm.indexOf('playRound('), bgm.indexOf('/** Mini Games'));
assert(!playRoundBlock.includes("'city_silly'"));
assert(bgm.includes("playMiniGame(): void") && bgm.includes("this.setTrack('city_silly')"));
assert(money.includes('presentationOwnsMoneyCue'));
assert(money.includes('packetMoneyCue'));
assert(presentation.includes("model.kind === 'tile_land' && model.tileType === 'money'"));
assert(dice.includes('DICE_FACES') && dice.includes('`${face} ${result}`'));
assert(!dice.includes('`🎲 ${result}`'));

assert(board048.includes('extends CareerMinigameBoardScene046'));
assert(board048.includes("disposition !== 'animate'"));
assert(!board048.includes('submitIntent('));
assert(!board048.includes('Math.random'));
assert(board056.includes('extends CareerMinigameBoardScene048'));
assert(!board056.includes('submitIntent('));
assert(!board056.includes('Math.random'));
assert(board0561.includes('extends CareerMinigameBoardScene056'));
assert(!board0561.includes('Math.random'));
assert(board0561.includes('showBranchPicker'));
assert(board057.includes('extends CareerMinigameBoardScene0561'));
assert(!board057.includes('Math.random'));
assert(board058.includes('extends CareerMinigameBoardScene057'));
assert(!board058.includes('Math.random'));
assert(board059.includes('extends CareerMinigameBoardScene058'));
assert(!board059.includes('Math.random'));
assert(!board059.includes('submitIntent('));
assert(board060.includes('extends CareerMinigameBoardScene059'));
assert(!board060.includes('Math.random'));
assert(!board060.includes('submitIntent('));
assert(board061.includes('extends CareerMinigameBoardScene060'));
assert(!board061.includes('Math.random'));
assert(!board061.includes('submitIntent('));
assert(board062.includes('extends CareerMinigameBoardScene061'));
assert(!board062.includes('Math.random'));
assert(!board062.includes('submitIntent('));
assert(board0651.includes('extends CareerMinigameBoardScene065'));
assert(board066.includes('extends CareerMinigameBoardScene0651'), '0.1.66 must keep the validated chain back to 0.1.48');
assert(!board066.includes('Math.random'), '0.1.66 wrapper must add no client RNG');
assert(board068.includes('extends CareerMinigameBoardScene067'), '0.1.68 must remain a presentation-only wrapper above the validated chain');
assert(!board068.includes('Math.random'), '0.1.68 wrapper must add no client RNG');
assert(board0681.includes('extends CareerMinigameBoardScene068'), '0.1.68.1 must remain presentation-only above 0.1.68');
assert(!board0681.includes('Math.random'), '0.1.68.1 readability wrapper must add no client RNG');
assert(!board0681.includes('submitIntent('), '0.1.68.1 readability wrapper must remain authority-free');
assert(board0682.includes('extends CareerMinigameBoardScene0681'), '0.1.68.2 must remain presentation-only above 0.1.68.1');
assert(!board0682.includes('Math.random'), '0.1.68.2 canonical UI wrapper must add no client RNG');
assert(!board0682.includes('submitIntent('), '0.1.68.2 canonical UI wrapper must remain authority-free');

// 0.1.66 human runtime found a CPU stall after a successful same-turn Jail/Hospital release.
// Permit exactly the guarded fresh-roll wake-up through the existing HOST intent path.
const executableSubmitCalls066 = board066.match(/internals\.submitIntent\(/g) ?? [];
assert.equal(executableSubmitCalls066.length, 1, '0.1.66 may execute only the guarded CPU fresh-roll intent');
assert(board066.includes("internals.submitIntent('roll', {})"));
assert(board066.includes('pendingCpuFreshRollAfterRelease066'));
assert(!releaseGuard066.includes('Math.random'));
assert(!releaseGuard066.includes('submitIntent('), 'guard helper must remain pure and authority-free');

assert(picker.includes('CHỌN LÁ BÀI') && picker.includes('DÙNG LÁ NÀY'));
assert(!picker.includes('CHỌN PHÉP THUẬT'));
assert(main.includes('TurnOrderScene048'));
assert(main.includes('CareerMinigameBoardScene0682 as ActiveBoardScene'));
assert.equal(MEMEME_BUILD.version, '0.1.68.2');
assert(lobby.includes('MEMEME_BUILD.lobbyHeader'), 'Lobby must use the canonical visible build source.');
assert(setup.includes('MEMEME_BUILD.setupHeader'), 'Setup must use the canonical visible build source.');
assert(lobby.includes('TIN TỨC / LÁ BÀI'), 'Current vocabulary must retain TIN TỨC / LÁ BÀI.');

console.log('[bugfix-pass-048] PASS money cue + true D6 + BGM isolation + stale token guard + guarded CPU release wake-up + vocabulary retained through 0.1.68.2');
