import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { MEMEME_BUILD } from '../src/buildInfo';

const main = readFileSync('src/main.ts', 'utf8');
const scene = readFileSync('src/scenes/CareerMinigameBoardScene0682.ts', 'utf8');
const scene069 = readFileSync('src/scenes/CareerMinigameBoardScene069.ts', 'utf8');
const scene0701 = readFileSync('src/scenes/CareerMinigameBoardScene0701.ts', 'utf8');
const scene07044 = readFileSync('src/scenes/CareerMinigameBoardScene07044.ts', 'utf8');
const jobPicker = readFileSync('src/ui/JobChoicePicker.ts', 'utf8');
const reactions = readFileSync('src/ui/ReactionSequencer.ts', 'utf8');
const presentationLayer = readFileSync('src/ui/MatchPresentationLayer.ts', 'utf8');
const presentationModel = readFileSync('src/ui/presentationModel.ts', 'utf8');
const visibleCopy = readFileSync('src/ui/friendlyVisibleCopy0701.ts', 'utf8');
const scene0561 = readFileSync('src/scenes/CareerMinigameBoardScene0561.ts', 'utf8');
const gamepad = readFileSync('src/ui/gamepadUiNavigation0651.ts', 'utf8');
const rules = readFileSync('docs/CANONICAL_UI_UX_RULES.md', 'utf8');

// Historical 0.1.68.2 UI guard: later canonical builds may advance the visible
// version while retaining this HUD/detail/safe-bubble contract.
const versionParts = MEMEME_BUILD.version.split('.').map(Number);
assert.equal(versionParts[0], 0);
assert.equal(versionParts[1], 1);
assert(versionParts[2] >= 69, `canonical runtime regressed below 0.1.69: ${MEMEME_BUILD.version}`);
assert(MEMEME_BUILD.phase.length > 0, 'canonical build phase must stay visible');
assert.match(main, /CareerMinigameBoardScene07044 as ActiveBoardScene/);
assert.match(scene07044, /extends CareerMinigameBoardScene0701/);
assert(!scene07044.includes('submitIntent(')); assert(!scene07044.includes('Math.random'));
assert.match(scene0701, /extends CareerMinigameBoardScene069/);
assert(!scene0701.includes('Math.random'));
assert.match(scene069, /extends CareerMinigameBoardScene0682/);
assert.match(scene, /extends CareerMinigameBoardScene0681/);
assert.match(scene, /IDLE_HUD_SCALE_0682 = 0\.9/);
assert.match(scene, /ACTIVE_HUD_SCALE_0682 = 1\.08/);
assert.match(scene, /syncStrictModalOwnership0682/);
assert.match(scene, /isAllowedModalAuxiliary0682/);
assert.match(scene, /root\.depth !== 910/);
assert.match(scene, /\[😐😄😤\]\/u/);
assert(!scene.includes('rootContainerDepth0682'), 'depth alone must never whitelist legacy modal text');
assert(!scene.includes('if (text.parentContainer) return;'), 'nested legacy text must not bypass modal ownership');
assert(!scene.includes('Math.random'));
assert(!scene.includes('submitIntent('));
assert.match(jobPicker, /CHẠM ĐỂ XEM/);
assert.match(jobPicker, /detailRoot/);
assert.doesNotMatch(jobPicker, /scene\.events\.on\('mememe-ui-back'/);
assert(!jobPicker.includes('Math.random'));
assert.match(gamepad, /events\.emit\('mememe-ui-back'\)/);
assert.match(reactions, /BUBBLE_SAFE_MARGIN_0682 = 18/);
assert.match(reactions, /Phaser\.Math\.Clamp/);
assert(!reactions.includes('Math.random'));
assert.match(presentationLayer, /addNaturalActionLine/);
assert.match(presentationLayer, /đưa \$\{amount\} B\$ cho/);
assert(!presentationLayer.includes("this.addPlayerChip(container, -322, 118"), 'technical ACTOR/TARGET chips must not render');
assert.match(presentationModel, /friendlyVisibleCopy0701/);
assert.match(visibleCopy, /người chơi khác/);
assert.match(visibleCopy, /NGƯỜI CHƠI KHÁC/);
assert.match(scene0561, /text\.startsWith\('SPACE roll'\)/);
assert.match(rules, /Idle player HUD is compact; active player HUD expands/);
assert.match(rules, /Job Hub uses compact cards plus optional details/);
assert.match(rules, /Soft rounded surfaces are the default shape language/);
console.log(`[canonical-ui-0682] PASS inherited active/idle HUD + strict modal ownership + safe reaction lanes under canonical ${MEMEME_BUILD.version}`);