import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { MEMEME_BUILD } from '../src/buildInfo';

const main = readFileSync('src/main.ts', 'utf8');
const splash = readFileSync('src/scenes/SplashScene069.ts', 'utf8');
const board = readFileSync('src/scenes/CareerMinigameBoardScene069.ts', 'utf8');
const lobby = readFileSync('src/scenes/LocalLobbyScene.ts', 'utf8');
const setup = readFileSync('src/scenes/SetupScene.ts', 'utf8');
const turnOrder = readFileSync('src/scenes/TurnOrderScene048.ts', 'utf8');
const css = readFileSync('src/firstImpression069.css', 'utf8');
const rules = readFileSync('docs/CANONICAL_UI_UX_RULES.md', 'utf8');
const packageJson = readFileSync('package.json', 'utf8');
const brandMaterializer = readFileSync('scripts/materialize-brand.mjs', 'utf8');
const CANONICAL_LOGO_SHA256 = '61219a2a4f25d71e097e52e4871c08a2d8f073726025ea756ef6e0fcaf40b08d';

assert.equal(MEMEME_BUILD.version, '0.1.69');
assert.equal(MEMEME_BUILD.phase, 'FIRST IMPRESSION POLISH');
assert.match(main, /SplashScene069,[\s\S]*LocalLobbyScene,[\s\S]*SetupScene,[\s\S]*TurnOrderScene,[\s\S]*ActiveBoardScene/);
assert.match(main, /CareerMinigameBoardScene069 as ActiveBoardScene/);
assert.match(packageJson, /materialize:brand/);
assert.match(packageJson, /prebuild[^\n]*materialize:brand/);
assert.match(brandMaterializer, /encoded\.length !== 95_220/);
assert.match(brandMaterializer, /data\.length !== 71_414/);
assert.match(brandMaterializer, /width !== 1024 \|\| height !== 1024/);
assert.match(brandMaterializer, new RegExp(CANONICAL_LOGO_SHA256));
assert(existsSync('public/assets/mememe-logo-official.webp'), 'canonical MeMeMe logo must be materialized before tests/package');
const logo = readFileSync('public/assets/mememe-logo-official.webp');
assert.equal(logo.length, 71_414, 'canonical logo byte count changed');
assert.equal(logo.subarray(0, 4).toString('ascii'), 'RIFF');
assert.equal(logo.subarray(8, 12).toString('ascii'), 'WEBP');
const readUint24LE = (offset: number) => logo[offset] | (logo[offset + 1] << 8) | (logo[offset + 2] << 16);
assert.equal(readUint24LE(24) + 1, 1024, 'canonical logo width changed');
assert.equal(readUint24LE(27) + 1, 1024, 'canonical logo height changed');
assert.equal(createHash('sha256').update(logo).digest('hex'), CANONICAL_LOGO_SHA256, 'canonical logo checksum changed');
assert.match(splash, /LOGO_URL_069\s*=\s*'assets\/mememe-logo-official\.webp\?v=canonical-1024-0693'/);
assert(!/LOGO_URL_069\s*=\s*['"]assets\/mememe-logo\.webp/.test(splash), 'runtime splash URL must never use the broken 500x500 export');
assert(!splash.includes("'Me³'"), 'temporary vector placeholder must not replace the official logo');
assert.match(splash, /CHẠM ĐỂ BẮT ĐẦU/);
assert.match(splash, /this\.scene\.start\('LocalLobbyScene'\)/);
assert(!splash.includes('Math.random'));

assert.match(board, /extends CareerMinigameBoardScene0682/);
assert.match(board, /ui\.meta\.setText\(''\)\.setVisible\(false\)/);
assert.match(board, /ownedJobLabels069/);
assert.match(board, /JOB_LABEL_WIDTH_069 = 184/);
assert.match(board, /fitJobLabel069/);
assert.match(board, /setMaxLines\(1\)/);
assert.match(board, /ACTIVE_SCALE_069 = 1\.14/);
assert.match(board, /resolveCameraActor0632/);
assert.match(board, /presentation069\(\)\?\.currentModel/);
assert.match(board, /🎲\$\{roll \? ` \$\{roll\}` : ''\} → NHẬN VIỆC/);
assert.match(board, /copy\.includes\('trúng'\)/);
assert.match(board, /hideLeakText069/);
assert(!board.includes('Math.random'));
assert(!board.includes('submitIntent('));

assert.match(lobby, /CHỌN CÁCH CHƠI/);
assert.match(lobby, /CHƠI NHANH/);
assert.match(lobby, /PRESERVE_SETUP_REGISTRY_KEY/);
assert.match(lobby, /consumePreserveSetup/);
assert(!lobby.includes('Vertical Slice đang khóa flow'));
assert.match(setup, /MEMEME_BUILD\.setupHeader/);
assert.match(MEMEME_BUILD.setupHeader, /TẠO NGƯỜI CHƠI/);
assert.match(setup, /Chạm ảnh để chọn mặt • Có thể bỏ qua/);
assert.match(setup, /setup-back-mode/);
assert.match(setup, /preserveSetup/);
assert.match(setup, /player\.faces\[expression\.id\]/);
assert.match(setup, /CHỌN ĐỘ DÀI/);
assert.match(turnOrder, /← QUAY LẠI/);
assert.match(turnOrder, /SetupScene', \{ preserve: true \}/);
assert(!setup.includes('Ảnh gốc chỉ tồn tại trong trình duyệt'));
assert(!setup.includes('Chọn độ dài trận. Mỗi người phải hoàn thành'));

assert.match(css, /border-radius:28px/);
assert.match(css, /border-radius:34px/);
assert.match(css, /setup-back-button/);
assert.match(rules, /Soft rounded surfaces are the default shape language/);
console.log('[first-impression-069] PASS canonical checksum-locked 1024 logo + presentation-actor HUD + leak-free Job result + reversible pre-game setup');
