import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { MEMEME_BUILD } from '../src/buildInfo';

const main = readFileSync('src/main.ts', 'utf8');
const splash = readFileSync('src/scenes/SplashScene069.ts', 'utf8');
const board = readFileSync('src/scenes/CareerMinigameBoardScene069.ts', 'utf8');
const lobby = readFileSync('src/scenes/LocalLobbyScene.ts', 'utf8');
const setup = readFileSync('src/scenes/SetupScene.ts', 'utf8');
const turnOrder = readFileSync('src/scenes/TurnOrderScene048.ts', 'utf8');
const css = readFileSync('src/firstImpression069.css', 'utf8');
const rules = readFileSync('docs/CANONICAL_UI_UX_RULES.md', 'utf8');
const packageJson = JSON.parse(readFileSync('package.json', 'utf8')) as { scripts?: Record<string, string> };

const runtimePatch = Number(MEMEME_BUILD.version.split('.')[2] ?? 0);
assert(Number.isInteger(runtimePatch) && runtimePatch >= 69, '0.1.69 presentation guard must accept later canonical runtimes');
assert.match(main, /SplashScene069,[\s\S]*LocalLobbyScene,[\s\S]*SetupScene,[\s\S]*TurnOrderScene,[\s\S]*ActiveBoardScene/);
assert.match(main, /CareerMinigameBoardScene069 as ActiveBoardScene/);

const logoPath = 'public/assets/mememe-logo-main.png';
assert(existsSync(logoPath), 'official MeMeMe 1024 PNG must be committed directly in public/assets');
const logo = readFileSync(logoPath);
assert(logo.length > 10_000, 'official logo PNG unexpectedly small');
assert.deepEqual([...logo.subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10], 'official logo must be a PNG');
assert.equal(logo.subarray(12, 16).toString('ascii'), 'IHDR', 'PNG must begin with IHDR');
assert.equal(logo.readUInt32BE(16), 1024, 'official logo width changed');
assert.equal(logo.readUInt32BE(20), 1024, 'official logo height changed');
const colorType = logo[25];
assert([4, 6].includes(colorType) || logo.includes(Buffer.from('tRNS')), 'official logo must preserve transparency');
assert.match(splash, /LOGO_URL_069\s*=\s*'assets\/mememe-logo-main\.png\?v=official-png-1024-0694'/);
assert(!splash.includes('mememe-logo-official.webp'), 'runtime splash must not use generated WebP brand payload');
assert(!/LOGO_URL_069\s*=\s*['"]assets\/mememe-logo\.webp/.test(splash), 'runtime splash must never use the broken 500x500 export');
assert(!splash.includes("'Me³'"), 'temporary vector placeholder must not replace the official logo');
assert.match(splash, /CHẠM ĐỂ BẮT ĐẦU/);
assert.match(splash, /this\.scene\.start\('LocalLobbyScene'\)/);
assert(!splash.includes('Math.random'));

assert.match(board, /extends CareerMinigameBoardScene0682/);
assert.match(board, /ui\.meta\.setText\(''\)\.setVisible\(false\)/);
assert.match(board, /ownedJobLabels069/);
assert.match(board, /JOB_LABEL_WIDTH_069 = 184/);
assert.match(board, /fitJobLabel069/);
assert.match(board, /setMaxLines\(1\)/);
assert.match(board, /ACTIVE_SCALE_069 = 1\.14/);
assert.match(board, /resolveCameraActor0632/);
assert.match(board, /presentation069\(\)\?\.currentModel/);
assert.match(board, /syncCardHandVisibility069/);
assert.match(board, /!browserSession\.isCpuSeat\(player\.id\)/);
assert.match(board, /runtime\.handButton\.setVisible\(visible\)/);
assert.match(board, /runtime\.handButtonText\?\.setVisible\(visible\)/);
assert.match(board, /setPosition\(0, -12\)/);
assert.match(board, /setPosition\(0, 48\)/);
assert.match(board, /copy\.includes\('trúng'\)/);
assert.match(board, /hideLeakText069/);
assert(!board.includes('Math.random'));
assert(!board.includes('submitIntent('));

assert.match(lobby, /CHỌN CÁCH CHƠI/);
assert.match(lobby, /CHƠI NHANH/);
assert.match(lobby, /PRESERVE_SETUP_REGISTRY_KEY/);
assert.match(lobby, /consumePreserveSetup/);
assert(!lobby.includes('Vertical Slice đang khóa flow'));
assert.match(setup, /MEMEME_BUILD\.setupHeader/);
assert.match(MEMEME_BUILD.setupHeader, /TẠO NGƯỜI CHƠI/);
assert.match(setup, /Chạm ảnh để chọn mặt • Có thể bỏ qua/);
assert.match(setup, /setup-back-mode/);
assert.match(setup, /preserveSetup/);
assert.match(setup, /player\.faces\[expression\.id\]/);
assert.match(setup, /player-role-row-069/);
assert.match(setup, /player-role-placeholder-069/);
assert.match(setup, /CHỌN ĐỘ DÀI/);
assert.match(turnOrder, /← QUAY LẠI/);
assert.match(turnOrder, /SetupScene', \{ preserve: true \}/);
assert(!setup.includes('Ảnh gốc chỉ tồn tại trong trình duyệt'));
assert(!setup.includes('Chọn độ dài trận. Mỗi người phải hoàn thành'));

assert.match(css, /border-radius:28px/);
assert.match(css, /border-radius:34px/);
assert.match(css, /setup-back-button/);
assert.match(css, /player-role-row-069 \{ min-height:30px/);
assert.match(css, /player-role-placeholder-069 \{ visibility:hidden/);
assert.match(rules, /Soft rounded surfaces are the default shape language/);
assert.match(rules, /mememe-logo-main\.png/);

const prebuild = packageJson.scripts?.prebuild ?? '';
assert(!prebuild.includes('materialize:brand'), 'normal build must not regenerate the manually committed official logo');
console.log('[first-impression-069] PASS committed logo + aligned setup + centered Job result + human-turn card UI + presentation-actor HUD');
