import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolveCameraActor0632 } from '../src/ui/cameraTarget0632';
import type { PresentationEventModel } from '../src/ui/presentationModel';

const mainSource = readFileSync(new URL('../src/main.ts', import.meta.url), 'utf8');
const scene0632Source = readFileSync(new URL('../src/scenes/CareerMinigameBoardScene0632.ts', import.meta.url), 'utf8');
const scene0631Source = readFileSync(new URL('../src/scenes/CareerMinigameBoardScene0631.ts', import.meta.url), 'utf8');
const scene069Source = readFileSync(new URL('../src/scenes/CareerMinigameBoardScene069.ts', import.meta.url), 'utf8');
const scene0701Source = readFileSync(new URL('../src/scenes/CareerMinigameBoardScene0701.ts', import.meta.url), 'utf8');
const authoritySource = readFileSync(new URL('../src/core/authority.ts', import.meta.url), 'utf8');

const movingP1 = { kind: 'move_step', actorId: 0 } as PresentationEventModel;
const landingP1 = { kind: 'tile_land', actorId: 0 } as PresentationEventModel;
assert.equal(resolveCameraActor0632(1, movingP1), 0);
assert.equal(resolveCameraActor0632(1, landingP1), 0);
assert.equal(resolveCameraActor0632(1, undefined), 1);
assert.equal(resolveCameraActor0632(undefined, movingP1), 0);
assert.equal(resolveCameraActor0632(undefined, undefined), undefined);
assert(mainSource.includes('CareerMinigameBoardScene07044 as ActiveBoardScene'));
assert(scene0701Source.includes('extends CareerMinigameBoardScene069'));
assert(!scene0701Source.includes('Math.random'));
assert(scene069Source.includes('extends CareerMinigameBoardScene0682'));
assert(!scene069Source.includes('submitIntent(')); assert(!scene069Source.includes('Math.random'));
assert(scene0632Source.includes('extends CareerMinigameBoardScene0631'));
assert(scene0632Source.includes('presentation?.currentModel'));
assert(scene0632Source.includes('this.lockCameraToPresentationActor0632();'));
assert(scene0632Source.includes('this.cameras.main.centerOn(token.x, token.y)'));
assert(scene0632Source.includes('if (internals.overviewMode) return;'));
assert(scene0631Source.includes('camera.setBounds(left, top, right - left, bottom - top)'));
assert(!scene0632Source.includes('submitIntent(')); assert(!scene0632Source.includes('Math.random'));
assert(authoritySource.includes('autoResolveParityBranches062'));
console.log('[movement-actor-camera-lock-0632] PASS historical movement-actor camera lock retained beneath 0.1.70.1 wrapper');