import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createInitialMatchState, type MatchEvent } from '../src/core/matchState';
import { pendingFreshMovementRollAfterRelease0701 } from '../src/core/releaseFlow0701';
import { buildPresentationModel } from '../src/ui/presentationModel';

const mainSource = readFileSync(new URL('../src/main.ts', import.meta.url), 'utf8');
const sceneSource = readFileSync(new URL('../src/scenes/CareerMinigameBoardScene0633.ts', import.meta.url), 'utf8');
const wrapperSource = readFileSync(new URL('../src/scenes/CareerMinigameBoardScene0634.ts', import.meta.url), 'utf8');
const directDiceSource = readFileSync(new URL('../src/scenes/DirectDiceBoardScene.ts', import.meta.url), 'utf8');
const cpuResumeSource = readFileSync(new URL('../src/core/cpuReleaseResume066.ts', import.meta.url), 'utf8');
const releaseFlowSource = readFileSync(new URL('../src/core/releaseFlow0701.ts', import.meta.url), 'utf8');
const scene069Source = readFileSync(new URL('../src/scenes/CareerMinigameBoardScene069.ts', import.meta.url), 'utf8');
const scene0701Source = readFileSync(new URL('../src/scenes/CareerMinigameBoardScene0701.ts', import.meta.url), 'utf8');
const replaySource = readFileSync(new URL('../src/core/replay.ts', import.meta.url), 'utf8');

assert(mainSource.includes('CareerMinigameBoardScene0701 as ActiveBoardScene'));
assert(scene0701Source.includes('extends CareerMinigameBoardScene069'));
assert(!scene0701Source.includes('Math.random'));
assert(scene069Source.includes('extends CareerMinigameBoardScene0682'));
assert(!scene069Source.includes('submitIntent(')); assert(!scene069Source.includes('Math.random'));
assert(wrapperSource.includes('extends CareerMinigameBoardScene0633'));
assert(sceneSource.includes('extends CareerMinigameBoardScene0632'));
assert(sceneSource.includes('runtime.showDeltaToast = () => undefined'));
assert(sceneSource.includes("model.kind === 'dice_roll' || model.kind === 'move_step'"));
assert(sceneSource.includes('if (movementStillPresenting) return;'));
assert(sceneSource.includes('RELEASE_CORRIDOR_FROM_0633'));
assert(sceneSource.includes('RELEASE_GATE_NODE_0633'));
assert(sceneSource.includes('return Promise.resolve()'));
assert(sceneSource.includes('duration: 430'));
assert(sceneSource.includes('fallback = this.time.delayedCall(650, finish)'));
assert(sceneSource.includes('onStop: finish'));
assert(sceneSource.includes('if (settled) return'));
assert(sceneSource.includes('installBoundedPresentationClose0633'));
assert(sceneSource.includes('this.time.delayedCall(320'));
assert(sceneSource.includes('originalFinishCurrent(false)'));
assert(!sceneSource.includes('releaseFreshRollArmed0633'));
assert(!sceneSource.includes('runtime.rollPendingTurn = undefined'));
assert(directDiceSource.includes('pendingFreshMovementRollAfterRelease0701'));
assert(!directDiceSource.includes('handledFreshReleaseEventSeq'));
assert(cpuResumeSource.includes('pendingFreshMovementRollAfterRelease0701'));
assert(releaseFlowSource.includes('event.actorId === actor.id'));
assert(replaySource.includes('// Release D6 is only the escape/recovery check. It must never become movement.'));
assert(replaySource.includes('ctx.state.turn.lastRoll = null;'));
assert(replaySource.includes("transition(ctx, 'PRE_ROLL_ACTION');"));

const match = createInitialMatchState({ boardId: 'release-presentation-0633', startNodeId: 0, playerNames: ['Ron'], seed: 633 });
match.turn.currentPlayerIndex = 0;
match.turn.turnNumber = 2;
match.turn.phase = 'PRE_ROLL_ACTION';
match.turn.lastRoll = null;
match.players[0]!.specialHold = undefined;
const releaseEvent: MatchEvent = { seq:10,type:'special_release',turnNumber:2,playerIndex:0,phase:'MOVING',revision:4,rngCalls:2,actorId:0,data:{location:'jail',result:3,success:true,title:'ĐƯỢC THẢ!',impact:'✅',description:'Thoát hành lang xong sẽ đổ một D6 di chuyển MỚI trong cùng lượt.',affectedPlayerIds:'0'} };
match.eventLog.push(releaseEvent);
const model = buildPresentationModel(releaseEvent, match.players);
assert(model); assert.equal(model.kind,'tile_land'); assert.equal(model.tileType,'special_release'); assert.equal(model.roll,3); assert.match(model.description,/CHỈ dùng để thoát/); assert.match(model.description,/D6 MỚI/);
assert.equal(pendingFreshMovementRollAfterRelease0701(match), 10, 'fresh movement D6 must be derived from authoritative release state even while presentation timing is independent');
match.players[0]!.specialHold = 'jail';
assert.equal(pendingFreshMovementRollAfterRelease0701(match), undefined, 'actor still held must never receive movement D6');
delete match.players[0]!.specialHold;
match.turn.lastRoll = 4;
assert.equal(pendingFreshMovementRollAfterRelease0701(match), undefined, 'already-consumed fresh D6 must not retrigger');
console.log('[presentation-release-sync-0633] PASS 0.1.70.1 launcher + single authoritative release detector + bounded modal/corridor presentation close');