import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const parity=readFileSync('src/scenes/PresentationParityBoardScene.ts','utf8');
const scene=readFileSync('src/scenes/CareerMinigameBoardScene07044.ts','utf8');
const settings=readFileSync('src/ui/SettingsPanel.ts','utf8');
const mini=readFileSync('src/ui/MiniGameOverlay.ts','utf8');
const vf=readFileSync('src/ui/visualFoundationMiniGameVf07.ts','utf8');
const scene063=readFileSync('src/scenes/CareerMinigameBoardScene063.ts','utf8');
assert.match(parity,/resolveCameraActor0632/);
assert.match(parity,/updateActiveTokenHalo\(presentationActorId \?\? player\.id\)/);
assert.match(scene,/runtime\.presentation\?\.isBlocking\(\) \? runtime\.presentation\.currentModel : undefined/);
assert.match(scene,/new Phaser\.GameObjects\.Text\(this, -322, -123, model\.eyebrow/);
assert.match(scene,/cinematic-kicker-ch141/);
assert.match(scene063,/root\.name === 'card-presentation-card' \|\| root\.name === 'news-presentation-card'/);
assert.match(settings,/suppressClosedSettingsSpaceCh141/);
assert.match(settings,/event\.preventDefault\(\)/);
assert.match(settings,/target\.blur\(\)/);
assert.match(vf,/shellRadius: 30/);
assert.match(vf,/surfaceRadius: 24/);
assert.match(vf,/chipRadius: 16/);
assert.match(mini,/function roundedSurfaceCh141/);
assert.match(mini,/function paintRoundedSurfaceCh141/);
assert.equal((mini.match(/scene\.add\.rectangle/g)??[]).length,1);
for(const name of ['vf07-minigame-shell-ch141','vf07-minigame-header-ch141','vf07-minigame-result-paper-ch141','vf07-majority-result-box-ch141','vf07-rps-card-left-ch141','vf07-rps-card-right-ch141','vf07-minigame-podium-paper-ch141']) assert.ok(mini.includes(name),name);
assert.doesNotMatch(mini,/Math\.random\s*\(/);
console.log('[runtime-polish-ch141] PASS actor spotlight + Space/settings isolation + shared Card/News header + rounded Mini Game surfaces');
